name: Build and Test

on:
  push:
    branches: [GmashaN-patch-2]
  pull_request:
    branches: [new_feature_408440]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        ref: new_feature_408440
    - name: Install Dependencies
      run: python -m pip install --upgrade pip

    - name: Run triangle test
      run: triangle_test.py
