name: Run tests

on:
  push:
    branches: [main]

jobs:
  testUbuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run triangle test
      run: python -m unittest triangle_test.py

    - name: Run circle test
      run: python -m unittest circle_test.py

    - name: Run square test
      run: python -m unittest square_test.py

    - name: Run rectangle test
      run: python -m unittest rectangle_test.py

  testWindows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run triangle test
      run: python -m unittest triangle_test.py

    - name: Run circle test
      run: python -m unittest circle_test.py

    - name: Run square test
      run: python -m unittest square_test.py

    - name: Run rectangle test
      run: python -m unittest rectangle_test.py
