name: Build and Test

on:
  push:
    branches: [new_feature_408440]
  pull_request:
    branches: [new_feature_408440]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@ee2113536afb7f793eed4ce60e8d3b26db912da4 # v1.127.0
        with:
          bundler-cache: true
      - name: Lint Ruby files
        run: bundle exec rubocop
  test:
    runs-on: [ubuntu-latest,windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python Environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run rectangle test
      run: python rectangle_test.py test

    - name: Run circle test  
      run: python circle_test.py test

    - name: Run triangle test
      run: python triangle_test.py test

    - name: Run square test
        python square_test.py test
