name: Build and Test

on:
  push:
    branches: [new_feature_408440]
  pull_request:
    branches: [new_feature_408440]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint $(git ls-files '*.py')
  test:
    needs: lint
    runs-on: [ubuntu-latest,windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python Environment
      uses: actions/setup-python@v3
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run rectangle test
      run: python rectangle_test.py test

    - name: Run circle test  
      run: python circle_test.py test

    - name: Run triangle test
      run: python triangle_test.py test
