name: Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: [ubuntu-latest,windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Python Environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
  
    - name: Run rectangle test
      run: python rectangle_test.py test

    - name: Run circle test  
      run: python circle_test.py test

    - name: Run triangle test
      run: python triangle_test.py test

    - name: Run square test
        python square_test.py test
